### ISSUE TITLE
Возврат старшей кости у игрока.

### ISSUE THREAD

**Issue by dzamakhaiev** [denyszamiatin/dominoes#17]
Исходя из правил:
"Если ни у кого из участников нет и кости 6-6, то первый ход с дубля 0-0. Если дублей нет вообще, то ход с кости 5-6, и так далее по убыванию значений костей."
необходимо найти и вернуть старшую кость у игрока для следующего сравнения с другими старшими костями игроков(или дублями).

Написать функцию для поиска старшей кости у игрока.

**Comment by Simperovych** [comment]
Добавил функцию find_oldest_bone, которая возвращает индекс профиля с наибольшей костью и индекс самой кости.
