### ISSUE TITLE
Сравнение не дублей у игроков

### ISSUE THREAD

**Issue by dzamakhaiev** [denyszamiatin/dominoes#18]
Исходя из правил:
"Если ни у кого из участников нет и кости 6-6, то первый ход с дубля 0-0. Если дублей нет вообще, то ход с кости 5-6, и так далее по убыванию значений костей."
возможен вариант отсутствия дублей у одного или нескольких игроков. 

Необходимо написать функцию, которая на вход получает либо дубли(и находит младший из них), либо дубли и старшие кости(и тогда старшие кости по сути не играют роли), либо только старшие кости(и вот здесь их нужно сравнивать по старшинству).

Возвращать либо самый младший дубль, либо старшую кость(если нет дублей и игроков).

**Comment by Simperovych** [comment]
Добавил функцию find_first_player которая возвращает или индекс профиля с младшим дублем или индекс профиля с старшей костьюю
