### ISSUE TITLE
Перемешивание костей

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/dominoes#2]
Написать фрагмент кода для перемешивания игровых костей (см. модуль random)

**Comment by DYurchenko** [comment]
У меня вопрос: при выборе костей мне тоже приходится их перемешивать.
Уже реализовано.

**Comment by AnatoliySt20** [comment]
сделано

**Comment by vladyege** [comment]
закрывай issue, чтоб не "висело"

**Comment by idrummer83** [comment]
я закрою, не обессудьте по братски
