### ISSUE TITLE
Отображение костей игрока

### ISSUE THREAD

**Issue by dzamakhaiev** [denyszamiatin/dominoes#20]
Написать функцию для отображение костей текущего игрока.

На вход id игрока. На выход ничего, все отображать в консоль.

**Comment by vladyege** [comment]
мы это уже сделали в главном цикле:
"Написать функцию, которая перебирает игроков, начиная с того, который ходит первым, выводит его кости на экран"

**Comment by dzamakhaiev** [comment]
Тогда нужно выделить написанный код в отдельную функцию. Одна функция - одно действие. Придерживаемся унитарного подхода.

**Comment by vladyege** [comment]
done
