### ISSUE TITLE
Добавление кости игроку при пропуске хода

### ISSUE THREAD

**Issue by dzamakhaiev** [denyszamiatin/dominoes#27]
Когда у игрока нет костей для хода, он берет из оставшихся костей(назовем "общак") по одной за раз.

Написать функцию для добавление кости в словарь игроку при пропуске им хода.
Проверить, что в общаке есть еще кости. Если есть, взять одну случайную, просто пропустить ход.

**Comment by KBH27** [comment]
Сделал проверку базара на наличие костей, добавление случайной кости игроку и удаление этой кости с базара.
Остался открытым вопрос входит ли описание функции пропуска хода в эту задачу?
В нашем коде я ее не нашел. По логике она должна быть реализована где-то в главном цикле.
Я попытался ее реализовать:
- распаковал кортежи, вложенные в список, в отдельный список
- убрал дубликаты значений, чтобы уменьшить количество сравнений 
- сравнить переменные (крайние числа на игровом столе) с списком (цифрами на костях игрока) не получилось. Но и не понятно нужно ли это делать в рамках этой задачи.

Самостоятельный блок этого кода с вводными и проверочными строками кода:

import random
left_points_on_table = 0
right_points_on_table = 6
players_bones = [(1, 3), (2, 3), (5, 5), (2, 5)]
bones_reserve = [(1, 4), (2, 5), (1, 6)]

# Перепаковываем кортежы, вложенные в список, просто в список:
list_players_bones = [j for i in players_bones for j in i]
# Оставляем в списке только уникальные цифры костей:
uniq_list_players_bones = set(list_players_bones)
#В этом цикле планируется (НЕ РАБОТАЕТ ИМЕННО ЦИКЛ): 
# 1. Сравниваем уникальные цифры игрока с крайними цифрами на столе
for x in uniq_list_players_bones:
    if left_points_on_table or right_points_on_table != uniq_list_players_bones:
#  2. Проверяем, не пустой ли базар:
        if bones_reserve:
#  3. Если нет, то забираем себе случайную кость с базара:
            players_bones.append(bones_reserve.pop(random.randint(0,len(bones_reserve)-1)))
#  4. Увеличием елемент для перебора цикла        
    x += 1 
 #  Цикл закончен, проверяем списки
print(players_bones)
print("/n")
print(bones_reserve)

**Comment by KBH27** [comment]
Евгений помог написать код правильно
