### ISSUE TITLE
Получить очередность всех игроков из словаря

### ISSUE THREAD

**Issue by dzamakhaiev** [denyszamiatin/dominoes#28]
Для того, чтобы каждый раз в главном цикле не обращаться в словарь для получения очередности игроков, написать функцию, которая возвращает список кортежей вида: 
[(порядковый номер, индекс игрока), ...  ]
Вернуть этот список отсортированным по порядку хода игроков.

**Comment by KBH27** [comment]
Я так понял порядковый номер и индекс игрока уже есть в словаре player_dict, поэтому сделал только сортировку. Если же эти элементы в разных кортежах, тогда можно попробовать такой вариант players_queue = sorted(list(zip(players_dict, second_list)))
