### ISSUE TITLE
Создание профилей игроков

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/dominoes#6]
Написать фрагмент кода для создания списка профелей игроков, которые соддержат списки выданных костей

**Comment by idrummer83** [comment]
нужно подумать в каком виде ты мне будешь отдавать список, например:
[user_name, [1,2],[1,2],[0,0]....[1,1]] и всё это должно быть в переменной.

**Comment by vladyege** [comment]
Привет! насколько я понял, у нас нет username. В зависимости от кол-ва участников, у нас будет столько же индексов в списке. Сам список состоит из подсписков - (сами кости).
[ [[1,2],[1,3].....], [[1,4],[1,5]...], [[1,6], [2,1]...] ]
приблизительный пример из трех игроков
таким образом, индекс 0 основного списка - это первый игрок, у которого кости [[1,2],[1,3].....],
индекс 1 - второй игрок и т.д.

**Comment by idrummer83** [comment]
я думаю тут без имени никак. смотри мне нужно вывести сообщение - "первым ходит игрок №2 (имя)" номер я ещё выведу а имя??? может сделать -  petya=[[1,2]....[3,2] ] и players_list=[petya,vasa,kolya]. кароче говоря 2 массива.

**Comment by vladyege** [comment]
а почему ты думаешь, что нужно имя. В задании такого нет. Я подходил в конце занятия уточнял у Дениса. Договорились работать с индексами. Если с именами, то это уже словари получаются, а не списки.

**Comment by idrummer83** [comment]
ок. передавай так. [ [[1,2],[1,3].....], [[1,4],[1,5]...], [[1,6], [2,1]...] ] --- беру за основу

**Comment by vladyege** [comment]
Юра, я забыл, как мы договорились, что нужно делать с issue в Github, когда
сделал задание? через Pycharm я его выгрузил.
Теперь close issue или это делает преподаватель. Я заметил, что твое
задание 7е исчезло.

2016-12-13 12:18 GMT+02:00 yura lyashenko <notifications@github.com>:

**Comment by idrummer83** [comment]
да закрывай. Так видно что таски выполняются. Если находится баг - таск заного переоткрывают или заводят новый. Везде по разному - для таких дел есть специальный софт где всё это дело документируется.

**Comment by vladyege** [comment]
Юра, привет. Я тебе написал в чат кое-что. Проверь, если что. Если вдруг
тебе неприятно, что я вмешиваюсь в issue,
скажи, я не буду.
спасибо

13 декабря 2016 г., 16:17 пользователь yura lyashenko <
notifications@github.com> написал:
